name: CI/CD Workflow for Spring Boot App with Docker
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/hello-world-app:latest'
      - name: Set up MySQL Docker container
        uses: 'docker://mysql:8'
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hello_world_db
        with:
          entrypoint:
            - docker-entrypoint.sh
            - mysqld
      - name: Run tests
        run: mvn test
